### ISSUE TITLE
rounding errors of time_of_day using the craftai.Time class

### ISSUE THREAD

**Issue by PierreSalaun** [craft-ai/craft-ai-client-js#126]
I choose to pass 'time of day' as a non generated feature for an agent, and I make the time of day myself using the craftai.Time constructor.

However I appear to have some rounding errors when I check the context operations.
For example, I have an operation at timestamp 
of 1498882800 (01/07/2017 06:20), but the resulting time of day appears to be 6.333333333333333, which results in "06:19:59" in the inspector.

**Comment by cloderic** [comment]
Should be fixed in v1.15.2 can you check @PierreSalaun ?

**Comment by PierreSalaun** [comment]
Now with the same example I have "06:19:60" displayed in the inspector (it was previously "06:19:59").

**Comment by PierreSalaun** [comment]
@giska can you take a look?
