### ISSUE TITLE
Support timezone as UTC offset in minutes

### ISSUE THREAD

**Issue by alexisfontaine** [craft-ai/craft-ai-client-js#130]
It's by far the most common way to define a specific time programmatically (at least in JavaScript see [native](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset), [Moment](http://momentjs.com/docs/#/manipulating/utc-offset/) or [Luxon](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-get-offset)).

The use of named offset is flawed (see [Luxon's documentation](https://moment.github.io/luxon/docs/manual/zones.html#terminology)) and [the client doesn't support all of them](https://github.com/craft-ai/craft-ai-client-js/blob/master/src/timezones.js#L3-L34) (like fixed-offset `UTC+7` or offsets with GMT `GMT+11`)

Besides the [conversion function already exists internally](https://github.com/craft-ai/craft-ai-client-js/blob/master/src/time.js#L9-L18) and it is frustrating having to rewrite it ourselves over and over.

**Comment by cloderic** [comment]
TODO -> Support number as a minute offset in the platform and on the different clients.

**Comment by cibeah** [comment]
Did a PR for the platform, requested your review @alexisfontaine , if that's ok will add other PRs for the client.

**Comment by Giska** [comment]
Missing doc update. @cibeah is on it !

**Comment by Giska** [comment]
Done in https://github.com/craft-ai/content/pull/129
