### ISSUE TITLE
Use the bulk API in the client

### ISSUE THREAD

**Issue by cloderic** [craft-ai/craft-ai-client-js#140]
# Definition of Done #

- [x] It is possible to create several agents at once
- [x] It is possible to destroy several agents at once
- [x] It is possible to add operations to several agents at once
- [x] It is possible to compute several decision trees at once

**Comment by yleprincecraft** [comment]
No test for the existing `deleteAgent` method in the js client ?

**Comment by Totoketchup** [comment]
@yleprincecraft This is done, right ?

**Comment by Giska** [comment]
@yleprincecraft Is it done ?
