### ISSUE TITLE
craft ai js client v2.0

### ISSUE THREAD

**Issue by cloderic** [craft-ai/craft-ai-client-js#142]
We have already identified stuffs that should be improved for this v2.

- [ ] Remove deprecated functions
- [ ] Add an explicit method `destroy` (or `terminate` to the client) to release hanging sockets
- [ ] Remove support for anything before Node v6
- [ ] Get rid of babel
- [ ] Find a way to run unit tests in the browser as part of the CI
- [x] Get rid of `moment` (#95)
- [x] Get rid of as much as possible from `lodash`
- [ ] Accept [iterators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) in functions taking a list of stuffs
- [ ] Better management of the rate limiting of the API #131 

Let us know what you'd like in this upcoming release.

**Comment by rmdh** [comment]
validation tools

**Comment by alexisfontaine** [comment]
Support taking decisions from operations #122.
