### ISSUE TITLE
Automatically transcode v2 format to v1 format

### ISSUE THREAD

**Issue by matthieu-boussard** [craft-ai/craft-ai-client-js#147]
# Objective # 

- front automaticaly transcode v2 trees to v1. 
- No API change 

# Definition of done # 
- [ ] `learning_front` can receive v1 or v2 tree
- [ ] `learning_front` transcode v2 to v1

**Comment by matthieu-boussard** [comment]
should be handled by treecache !

**Comment by Totoketchup** [comment]
To modify:
- Multi split -> repeat
- distribution -> bin
- nb_sample -> bin

impossible to appear:
- boolean type
- null branch
- optional branch

Do we have v2 -> v1 = v1 ? Might not be the case with multi-split enum!
