### ISSUE TITLE
Adding context operations to an agent delays the end of the script

### ISSUE THREAD

**Issue by alexisfontaine** [craft-ai/craft-ai-client-js#91]
Here is a simple example to illustrate the issue.

Commenting out the block where context operations are added to the agent or forcing the method to flush, make the script end as expected.

It is related to the use of the Lodash method `throttle` in [src/client.js#L103](https://github.com/craft-ai/craft-ai-client-js/blob/master/src/client.js#L103). It seems that this function waits for an additional tick before ending.

<details>
    <summary>Source</summary>

```javascript
require('dotenv').config()


const CraftAi = require('craft-ai')
const Debug = require('debug')


const agentId = process.env.AGENT_ID
const craftAi = CraftAi.createClient(process.env.CRAFT_TOKEN)
const log = Debug(agentId)

log('Starting')

craftAi
	.deleteAgent(agentId)
	.then(() => {
		log('Creating agent')
		
		return craftAi.createAgent({
			context: { output: { type: 'continuous' } },
			output: ['output']
		}, agentId)
	})
	.then(agent => {
		log('Adding context operations')
		
		const contextOperations = new Array(10).fill(null).map(generateContextOperations)

		return craftAi.addAgentContextOperations(agentId, contextOperations)
	})
	.then(() => log('Done'))
	.catch(console.error)

function generateContextOperations (_, index) {
	return {
		timestamp: Date.now() / 1000 + index,
		context: { output: Math.random() }
	}
}
```
</details><br>

In addition, there is no way to know for sure when the operations have been successfully sent to craft.ai. Either we wait for an additional 1 minute (the [default setting](https://github.com/craft-ai/craft-ai-client-js/blob/master/src/defaults.js#L4)) or we wait for the online inspector to refresh after it gets the SSE.

**Comment by cloderic** [comment]
Fixed by #98
