### ISSUE TITLE
`addAgentContextOperations` resolves with `undefined`

### ISSUE THREAD

**Issue by alexisfontaine** [craft-ai/craft-ai-client-js#97]
The documentation suggests that the method `addAgentContextOperations` of the client resolves with the agent itself (see [here](https://beta.craft.ai/doc/js#4---add-context-operations)).

Its actual behavior is rather different: [src/client.js#L80](https://github.com/craft-ai/craft-ai-client-js/blob/master/src/client.js#L80).

**By the way**, the flushing mechanism is quite useless and misleading.

**Comment by cloderic** [comment]
- The documentation needs to fixed (it's ongoing).
- Let's talk about the flushing.

**Comment by alexisfontaine** [comment]
The context operations buffering is also responsible for https://github.com/craft-ai/craft-ai-client-js/issues/91.
